name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full Git history is cloned so the commit hash can be retrieved

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip ninja-build meson g++ pkg-config catch2

      # Configure and build the project using Meson
      - name: Configure and build
        run: |
          meson setup build
          meson compile -C build

      # Run tests
      - name: Run tests
        run: meson test -C build --print-errorlogs